import { BoardData } from './types';

export const INITIAL_BOARD_DATA: BoardData = {
  assignees: {
    'user-1': { id: 'user-1', name: 'Alice', avatarUrl: 'https://picsum.photos/seed/alice/32/32' },
    'user-2': { id: 'user-2', name: 'Bob', avatarUrl: 'https://picsum.photos/seed/bob/32/32' },
    'user-3': { id: 'user-3', name: 'Charlie', avatarUrl: 'https://picsum.photos/seed/charlie/32/32' },
    'user-4': { id: 'user-4', name: 'Diana', avatarUrl: 'https://picsum.photos/seed/diana/32/32' },
  },
  tasks: {
    'task-1': { id: 'task-1', title: 'Design landing page mockups', dueDate: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(), assigneeId: 'user-1', priority: 'High', isCompleted: false, columnId: 'col-2' },
    'task-2': { id: 'task-2', title: 'Develop user authentication', dueDate: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(), assigneeId: 'user-2', priority: 'High', isCompleted: false, columnId: 'col-2' },
    'task-3': { id: 'task-3', title: 'Setup database schema', dueDate: new Date(new Date().setDate(new Date().getDate())).toISOString(), assigneeId: 'user-2', priority: 'Medium', isCompleted: true, columnId: 'col-7' },
    'task-4': { id: 'task-4', title: 'Write API documentation', dueDate: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(), assigneeId: 'user-3', priority: 'Low', isCompleted: false, columnId: 'col-1' },
    'task-5': { id: 'task-5', title: 'Create marketing copy', dueDate: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(), assigneeId: 'user-4', priority: 'Medium', isCompleted: false, columnId: 'col-3' },
    'task-6': { id: 'task-6', title: 'Review frontend code', dueDate: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(), assigneeId: 'user-1', priority: 'High', isCompleted: false, columnId: 'col-4' },
    'task-7': { id: 'task-7', title: 'Deploy to staging server', dueDate: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(), assigneeId: 'user-2', priority: 'High', isCompleted: false, columnId: 'col-1' },
    'task-8': { id: 'task-8', title: 'Onboarding flow design', dueDate: new Date(new Date().setDate(new Date().getDate() + 4)).toISOString(), assigneeId: 'user-1', priority: 'Medium', isCompleted: false, columnId: 'col-3' },
    'task-9': { id: 'task-9', title: 'Fix login bug', dueDate: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(), assigneeId: 'user-2', priority: 'High', isCompleted: false, columnId: 'col-5' },
    'task-10': { id: 'task-10', title: 'Research competitors', dueDate: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(), assigneeId: 'user-4', priority: 'Low', isCompleted: true, columnId: 'col-7' },
  },
  columns: {
    'col-1': { id: 'col-1', title: 'Backlog', taskIds: ['task-4', 'task-7'] },
    'col-2': { id: 'col-2', title: 'To-Do', taskIds: ['task-1', 'task-2'] },
    'col-3': { id: 'col-3', title: 'In Progress', taskIds: ['task-5', 'task-8'] },
    'col-4': { id: 'col-4', title: 'In Review', taskIds: ['task-6'] },
    'col-5': { id: 'col-5', title: 'Blocked', taskIds: ['task-9'] },
    'col-6': { id: 'col-6', title: 'Needs Info', taskIds: [] },
    'col-7': { id: 'col-7', title: 'Done', taskIds: ['task-3', 'task-10'] },
    'col-8': { id: 'col-8', title: 'Archived', taskIds: [] },
  },
  boards: {
    'board-1': { id: 'board-1', name: 'Q4 Marketing Campaign', columnIds: ['col-1', 'col-2', 'col-3', 'col-4', 'col-5', 'col-6', 'col-7', 'col-8'] },
    'board-2': { id: 'board-2', name: 'Website Redesign', columnIds: [] },
    'board-3': { id: 'board-3', name: 'Mobile App Launch', columnIds: [] },
  },
  notes: {},
  users: {
    'user-101': { id: 'user-101', name: 'Roshan Garrison', email: 'Roshan.Garrison@email.com', userId: '957398807', created: '2019-01-22T00:00:00Z', lastEdited: '2019-06-12T00:00:00Z', status: 'Denied' },
    'user-102': { id: 'user-102', name: 'Patricia Wolf', email: 'Wolf.Patricia.2@email.com', userId: '823756499', created: '2019-02-13T00:00:00Z', lastEdited: '2019-06-09T00:00:00Z', status: 'Denied' },
    'user-103': { id: 'user-103', name: 'Henry Matthews', email: 'H.Matthews@email.com', userId: '829103841', created: '2019-04-28T00:00:00Z', lastEdited: '2019-06-05T00:00:00Z', status: 'Denied' },
    'user-104': { id: 'user-104', name: 'Haider Cortez', email: 'Cortez.Haider@email.com', userId: '957398807', created: '2019-04-22T00:00:00Z', lastEdited: '2019-06-02T00:00:00Z', status: 'Approved' },
    'user-105': { id: 'user-105', name: 'Howard Walters', email: 'Walter9@email.com', userId: '957375807', created: '2019-07-18T00:00:00Z', lastEdited: '2019-06-01T00:00:00Z', status: 'Denied' },
    'user-106': { id: 'user-106', name: 'Mabel York', email: 'York.Mabel12@email.com', userId: '098737548', created: '2018-11-20T00:00:00Z', lastEdited: '2019-05-22T00:00:00Z', status: 'Approved' },
    'user-107': { id: 'user-107', name: 'Roy Morton', email: 'Morton323@email.com', userId: '957398807', created: '2019-10-13T00:00:00Z', lastEdited: '2019-05-18T00:00:00Z', status: 'Approved' },
    'user-108': { id: 'user-108', name: 'Violet Hodges', email: 'Violet.r.Hodges@email.com', userId: '183746578', created: '2018-05-02T00:00:00Z', lastEdited: '2019-05-17T00:00:00Z', status: 'Denied' },
    'user-109': { id: 'user-109', name: 'Amber Poole', email: 'Poole.a@email.com', userId: '957398807', created: '2019-01-11T00:00:00Z', lastEdited: '2019-05-14T00:00:00Z', status: 'Approved' },
  },
  tickets: {
    'ticket-1': { id: 'ticket-1', title: 'Cannot reset password', reporter: 'Alice', status: 'Open', userId: 'USR-101' },
    'ticket-2': { id: 'ticket-2', title: 'Page not loading on mobile', reporter: 'Bob', status: 'Open', userId: 'USR-102' },
    'ticket-3': { id: 'ticket-3', title: 'Export to CSV is failing', reporter: 'Charlie', status: 'In Progress', userId: 'USR-103' },
    'ticket-4': { id: 'ticket-4', title: 'Typo on the pricing page', reporter: 'Diana', status: 'Closed', userId: 'USR-104' },
  },
  emails: {
    'email-1': {
      id: 'email-1',
      sender: 'Alice',
      senderEmail: 'alice@example.com',
      subject: 'Re: Project Mockups - Feedback',
      body: `Hi team,\n\nJust reviewed the landing page mockups. They look fantastic! I've attached a few minor notes on the color palette for the CTA button.\n\nLet me know what you think.\n\nBest,\nAlice`,
      timestamp: new Date(new Date().setDate(new Date().getDate())).toISOString(),
      isRead: false,
      avatarUrl: 'https://picsum.photos/seed/alice/32/32',
    },
    'email-2': {
      id: 'email-2',
      sender: 'Bob',
      senderEmail: 'bob@example.com',
      subject: 'User Authentication System Deployed',
      body: `Hello,\n\nThe new user authentication service has been successfully deployed to the staging environment. Please proceed with testing.\n\nCredentials are in the shared vault.\n\nThanks,\nBob`,
      timestamp: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
      isRead: true,
      avatarUrl: 'https://picsum.photos/seed/bob/32/32',
    },
    'email-3': {
      id: 'email-3',
      sender: 'Charlie',
      senderEmail: 'charlie@example.com',
      subject: 'API Documentation Draft',
      body: `Hey,\n\nHere is the first draft of the API documentation as requested. It covers all the main endpoints for the user and project services.\n\nPlease review it when you have a moment.\n\nCheers,\nCharlie`,
      timestamp: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
      isRead: false,
      avatarUrl: 'https://picsum.photos/seed/charlie/32/32',
    },
     'email-4': {
      id: 'email-4',
      sender: 'Diana',
      senderEmail: 'diana@example.com',
      subject: 'Marketing Copy for Q4 Campaign',
      body: `Hi all,\n\nAttached is the final version of the marketing copy for the upcoming Q4 campaign. We've incorporated the feedback from the last review session.\n\nWe are on track for the launch next week!\n\nRegards,\nDiana`,
      timestamp: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
      isRead: true,
      avatarUrl: 'https://picsum.photos/seed/diana/32/32',
    },
  }
};